#include <boost/assign.hpp>

#include "KeyNames.h"

std::map<sf::Keyboard::Key, std::string> gun::KeyNames::MAP = boost::assign::map_list_of 
	(sf::Keyboard::A, "A")
	(sf::Keyboard::B, "B")
	(sf::Keyboard::C, "C")
	(sf::Keyboard::D, "D")
	(sf::Keyboard::E, "E")
	(sf::Keyboard::F, "F")
	(sf::Keyboard::G, "G")
	(sf::Keyboard::H, "H")
	(sf::Keyboard::I, "I")
	(sf::Keyboard::J, "J")
	(sf::Keyboard::K, "K")
	(sf::Keyboard::L, "L")
	(sf::Keyboard::M, "M")
	(sf::Keyboard::N, "N")
	(sf::Keyboard::O, "O")
	(sf::Keyboard::P, "P")
	(sf::Keyboard::Q, "Q")
	(sf::Keyboard::R, "R")
	(sf::Keyboard::S, "S")
	(sf::Keyboard::T, "T")
	(sf::Keyboard::U, "U")
	(sf::Keyboard::V, "V")
	(sf::Keyboard::W, "W")
	(sf::Keyboard::X, "X")
	(sf::Keyboard::Y, "Y")
	(sf::Keyboard::Z, "Z")
	(sf::Keyboard::Num0, "0")
	(sf::Keyboard::Num1, "1")
	(sf::Keyboard::Num2, "2")
	(sf::Keyboard::Num3, "3")
	(sf::Keyboard::Num4, "4")
	(sf::Keyboard::Num5, "5")
	(sf::Keyboard::Num6, "6")
	(sf::Keyboard::Num7, "7")
	(sf::Keyboard::Num8, "8")
	(sf::Keyboard::Num9, "9")
	(sf::Keyboard::Tilde, "Tilde")
	(sf::Keyboard::Dash, "-")
	(sf::Keyboard::Add, "+")
	(sf::Keyboard::Slash, "/")
	(sf::Keyboard::BackSlash, "Backslash")
	(sf::Keyboard::LBracket, "Left Bracket")
	(sf::Keyboard::RBracket, "Right Bracket")
	(sf::Keyboard::SemiColon, "Semicolon")
	(sf::Keyboard::Quote, "Quote")
	(sf::Keyboard::Comma, ",")
	(sf::Keyboard::Period, ".")
	(sf::Keyboard::Numpad0, "Numpad 0")
	(sf::Keyboard::Numpad1, "Numpad 1")
	(sf::Keyboard::Numpad2, "Numpad 2")
	(sf::Keyboard::Numpad3, "Numpad 3")
	(sf::Keyboard::Numpad4, "Numpad 4")
	(sf::Keyboard::Numpad5, "Numpad 5")
	(sf::Keyboard::Numpad6, "Numpad 6")
	(sf::Keyboard::Numpad7, "Numpad 7")
	(sf::Keyboard::Numpad8, "Numpad 8")
	(sf::Keyboard::Numpad9, "Numpad 9")
	(sf::Keyboard::F1, "F1")
	(sf::Keyboard::F2, "F2")
	(sf::Keyboard::F3, "F3")
	(sf::Keyboard::F4, "F4")
	(sf::Keyboard::F5, "F5")
	(sf::Keyboard::F6, "F6")
	(sf::Keyboard::F7, "F7")
	(sf::Keyboard::F8, "F8")
	(sf::Keyboard::F9, "F9")
	(sf::Keyboard::F10, "F10")
	(sf::Keyboard::F11, "F11")
	(sf::Keyboard::F12, "F12")
	(sf::Keyboard::Up, "Up Arrow")
	(sf::Keyboard::Down, "Down Arrow")
	(sf::Keyboard::Left, "Left Arrow")
	(sf::Keyboard::Right, "Right Arrow")
	(sf::Keyboard::Insert, "Insert")
	(sf::Keyboard::Home, "Home")
	(sf::Keyboard::Delete, "Delete")
	(sf::Keyboard::End, "End")
	(sf::Keyboard::PageUp, "Page Up")
	(sf::Keyboard::PageDown, "Page Down")
	(sf::Keyboard::Back, "Backspace")
	(sf::Keyboard::Return, "Return")
	(sf::Keyboard::Tab, "Tab")
	(sf::Keyboard::LShift, "Left Shift")
	(sf::Keyboard::RShift, "Right Shift")
	(sf::Keyboard::LControl, "Left Control")
	(sf::Keyboard::RControl, "Right Control")
	(sf::Keyboard::LAlt, "Left Alt")
	(sf::Keyboard::RAlt, "Right Alt")
	(sf::Keyboard::Space, "Space");